#this is context properties
#Tue Mar 03 22:47:11 CET 2026
new1=
ecotrack_dw_AdditionalParams=
ecotrack_dw_Database=ecotrack
ecotrack_dw_Login=postgres
ecotrack_dw_Password=enc\:routine.encryption.key.v1\:sHSVuLvs8RWqXs0vtN2Wl4khrJGObe68ZLLkykX6ELl91g\=\=
ecotrack_dw_Port=5432
ecotrack_dw_Schema=dw
ecotrack_dw_Server=
PARAMS_LOG_AdditionalParams=
PARAMS_LOG_Database=ecotrack
PARAMS_LOG_Login=postgres
PARAMS_LOG_Password=enc\:routine.encryption.key.v1\:6fCL8/QP2oFR7cmg4UnPnFYHr6Eywaz4N0GiPsAzpWCdYQ\=\=
PARAMS_LOG_Port=5432
PARAMS_LOG_Schema=PARAMS_LOG
PARAMS_LOG_Server=localhost
archiveFolder=D\:\\DATA_ECOTRACK\\archive\\
encodage=UTF-8
fieldSeparator=,
projectFolder=D\:\\DATA_ECOTRACK\\data\\
rejectFolder=D\:\\DATA_ECOTRACK\\reject\\
ecotrack_dw1_Server=ep-weathered-cherry-aies0456-pooler.c-4.us-east-1.aws.neon.tech
ecotrack_dw1_Login=neondb_owner
ecotrack_dw1_Database=neondb
ecotrack_dw1_Password=enc\:routine.encryption.key.v1\:nK4caMRxltGCFt0TTNRCFHXVDSeBiLzaajzZ/7ruS1fLE1uZ4gaUw15uUjc\=
ecotrack_dw1_AdditionalParams=neondb?sslmode\=require&channel_binding\=require
ecotrack_dw1_Port=5432
ecotrack_dw1_Schema=dw
