#this is context properties
#Wed Mar 04 00:24:53 CET 2026
ecotrack_dw1_Server=ep-weathered-cherry-aies0456-pooler.c-4.us-east-1.aws.neon.tech
ecotrack_dw1_Login=neondb_owner
ecotrack_dw1_Database=neondb
ecotrack_dw1_Password=enc\:routine.encryption.key.v1\:ypUtjAVG3ot574mKaDUHrtPjDh/Jch3ezS5z2JyTSSA5bpB4kQxYm5HYTiQ\=
ecotrack_dw1_AdditionalParams=neondb?sslmode\=require&channel_binding\=require
ecotrack_dw1_Port=5432
ecotrack_dw1_Schema=dw
