

services:

  dbt:
    build:
      context: .
      dockerfile: docker/dbt/Dockerfile
    container_name: ecotrack_dbt

    env_file:
      - .env

    volumes:
      - ./dbt:/usr/app/dbt
      - ./docker/dbt/profiles.yml:/root/.dbt/profiles.yml

    working_dir: /usr/app/dbt/ecotrack_dbt