#this is context properties
#Mon Mar 02 02:11:08 CET 2026
PARAMS_LOG_Login=postgres
PARAMS_LOG_Port=5432
PARAMS_LOG_Password=enc\:routine.encryption.key.v1\:Oja4VmtOTGQqZHcqGmve0bDLDePLuJPkhm3HEUGMfJEEGg\=\=
PARAMS_LOG_Database=ecotrack
PARAMS_LOG_AdditionalParams=
PARAMS_LOG_Schema=PARAMS_LOG
PARAMS_LOG_Server=localhost
ecotrack_dw_AdditionalParams=
ecotrack_dw_Schema=dw
ecotrack_dw_Database=ecotrack
ecotrack_dw_Password=enc\:routine.encryption.key.v1\:D8MPB+bmgc3ur16gpkGgOzwLadIjp9OFnItyyUD0irp8xQ\=\=
ecotrack_dw_Server=
ecotrack_dw_Login=postgres
ecotrack_dw_Port=5432
ecotrack_dw1_Server=ep-weathered-cherry-aies0456-pooler.c-4.us-east-1.aws.neon.tech
ecotrack_dw1_Login=neondb_owner
ecotrack_dw1_Database=neondb
ecotrack_dw1_Password=enc\:routine.encryption.key.v1\:/iYtu7QTJFjsw45WqXRf3X2gkNo3c+GlVlxtzrCOvOYlWPrOuFgwJJmGU6g\=
ecotrack_dw1_AdditionalParams=neondb?sslmode\=require&channel_binding\=require
ecotrack_dw1_Port=5432
ecotrack_dw1_Schema=dw
