#this is context properties
#Wed Mar 04 10:52:19 CET 2026
new1=
ecotrack_dw_AdditionalParams=
ecotrack_dw_Database=ecotrack
ecotrack_dw_Login=postgres
ecotrack_dw_Password=enc\:routine.encryption.key.v1\:s2zGPr5oMC8U2Y9grfQGeEetLUUsmtgeEEtL0cttXC5sUg\=\=
ecotrack_dw_Port=5432
ecotrack_dw_Schema=dw
ecotrack_dw_Server=
PARAMS_LOG_AdditionalParams=
PARAMS_LOG_Database=ecotrack
PARAMS_LOG_Login=postgres
PARAMS_LOG_Password=enc\:routine.encryption.key.v1\:gBDvcr/RWoRk9W+rwtCsthSYBlJ8sVD3WxMkWcHP1Hhl7A\=\=
PARAMS_LOG_Port=5432
PARAMS_LOG_Schema=PARAMS_LOG
PARAMS_LOG_Server=localhost
archiveFolder=D\:\\DATA_ECOTRACK\\archive\\
encodage=UTF-8
fieldSeparator=,
projectFolder=D\:\\DATA_ECOTRACK\\data\\
rejectFolder=D\:\\DATA_ECOTRACK\\reject\\
ecotrack_dw1_Server=ep-weathered-cherry-aies0456-pooler.c-4.us-east-1.aws.neon.tech
ecotrack_dw1_Login=neondb_owner
ecotrack_dw1_Database=neondb
ecotrack_dw1_Password=enc\:routine.encryption.key.v1\:r5W9pUl5kCDgh6tqzPe95zqe8m0rrnOduOxFxvyjQxwdK7U8Otkf5elh7c8\=
ecotrack_dw1_AdditionalParams=neondb?sslmode\=require&channel_binding\=require
ecotrack_dw1_Port=5432
ecotrack_dw1_Schema=dw
