#this is context properties
#Mon Mar 02 10:57:50 CET 2026
new1=
ecotrack_dw_AdditionalParams=
ecotrack_dw_Database=ecotrack
ecotrack_dw_Login=postgres
ecotrack_dw_Password=enc\:routine.encryption.key.v1\:yomOhJMjHPgsXs0DRT7s7cZIouYzttsbAbl/ORk+ofvRCw\=\=
ecotrack_dw_Port=5432
ecotrack_dw_Schema=dw
ecotrack_dw_Server=
PARAMS_LOG_AdditionalParams=
PARAMS_LOG_Database=ecotrack
PARAMS_LOG_Login=postgres
PARAMS_LOG_Password=enc\:routine.encryption.key.v1\:TfGU2VQFOm0M3/gQDZ8/jltUryOPiJ8IRmz1WMCiuJbYFA\=\=
PARAMS_LOG_Port=5432
PARAMS_LOG_Schema=PARAMS_LOG
PARAMS_LOG_Server=localhost
archiveFolder=D\:\\DATA_ECOTRACK\\archive\\
encodage=UTF-8
fieldSeparator=,
projectFolder=D\:\\DATA_ECOTRACK\\data\\
rejectFolder=D\:\\DATA_ECOTRACK\\reject\\
ecotrack_dw1_Server=ep-weathered-cherry-aies0456-pooler.c-4.us-east-1.aws.neon.tech
ecotrack_dw1_Login=neondb_owner
ecotrack_dw1_Database=neondb
ecotrack_dw1_Password=enc\:routine.encryption.key.v1\:SRXz6CpJc4i2ctK/g6JiIlxC3OFm9NJGQy46tIBOD3DclFUwRV8UuqFkCKk\=
ecotrack_dw1_AdditionalParams=neondb?sslmode\=require&channel_binding\=require
ecotrack_dw1_Port=5432
ecotrack_dw1_Schema=dw
